DD/urls.py
from django.urls import path

from . import views

app_name = 'DD'

urlpatterns = [
    path('', views.customer_packages_all, name='customer_packages_all'),
    path('package/<slug:slug>/', views.package_detail, name='package_detail'),
    path('package-tracking/<slug:package_slug>/', views.user_track_packages, name='user_track_packages'),
    path('driver/routes/', views.driver_route, name='driver_route'),
    path('driver/packages', views.driver_packages, name='driver_packages'),
    path('customer/timeframe', views.customer_edit_timeframe, name='customer_edit_timeframe'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DD.urls', namespace='DD')),
    path('', include('custom_auth.urls', namespace='custom_auth')),
    path('', include('custom_api.urls', namespace='custom_api')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path("accounts/register/", views.register_request, name="register"),
    path("accounts/login/", views.login_request, name="login"),
    path("accounts/logout/", views.logout_request, name= "logout"),
]

DD/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



# Create your models here.

class Available_days(models.Model):
        days = (
        ('SUNDAY', 'Sunday'),
        ('MONDAY', 'Monday'),
        ('TUESDAY', 'Tuesday'),
        ('WEDNESDAY', 'Wednesday'),
        ('THURSDAY', 'Thursday'),
        ('FRIDAY', 'Friday'),
        ('SATURDAY', 'Saturday'),
    )
        
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None, 
                                null=True, related_name='customer')
    first_name = models.CharField(max_length=255)    
    last_name = models.CharField(max_length=255)    
    slug = models.SlugField(max_length=255, null=True)
    
    street_and_number = models.CharField(max_length=255, default='Nothing')
    zipcode = models.CharField(max_length=255, default='1111')
    city = models.CharField(max_length=255, default='Groningen')
    country = models.CharField(max_length=255, default='Netherlands')

    part_of_day = (
        ('MORNING', 'Morning'),
        ('AFTERNOON', 'Afternoon'),
        ('EVENING', 'Evening')
    )
    
    #available_days = models.ManyToManyField(Available_days)
    available_days = models.CharField(max_length=50, default='Monday')
    available_parts_days = models.CharField(max_length=50, choices=part_of_day, default='Morning')

    
    def get_absolute_url(self):
        return reverse("DD:Customer_detail",args=[self.slug])
    
    def __str__(self):
        return self.first_name + self.last_name
    
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None, 
                                null=False, related_name='employee')
    first_name = models.CharField(max_length=255)    
    last_name = models.CharField(max_length=255)  
    salary = models.FloatField(default=0.0)
    
    DRIVER = 'DRIVER'
    WHW = 'WAREHOUSE WORKER'
    WHM = 'WAREHOUSE MANAGER'
    available_positions = (
        (DRIVER, 'Driver'),
        (WHW, 'Warehouse Worker'),
        (WHM, 'Warehouse Manager')
    )
    
    VAN = 'VAN'
    BIKE = 'BICYCLE'
    available_vehicles = (
        (VAN, 'Van'),
        (BIKE, 'Bicycle')
    )
    
    position = models.CharField(max_length=50, choices=available_positions)
    vehicle = models.CharField(max_length=50, choices=available_vehicles, blank=True, default='')
    slug = models.SlugField(max_length=255, null=True)
    
    class Meta:
        verbose_name_plural = 'Employees'
        
    def get_absolute_url(self):
        return reverse("DD:Employee_detail",args=[self.slug])
    
    def __str__(self):
        return self.first_name + self.last_name
    
class Delivery(models.Model):
    order_id = models.IntegerField(default=50, primary_key=True)
    expected_delivery_datetime = models.DateTimeField(auto_now=False)
    actual_delivery_datetime = models.DateTimeField(auto_now=False)
    cost_in_cents = models.FloatField(default=0.0)
    
    class Meta:
        verbose_name_plural = 'Deliveries'
        
    def __str__(self):
        return 'order: ' + str(self.order_id)
    
class Package(models.Model):
    purchased_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='package_creator')
    delivered_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='package_deliverer')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
        
    DELIV = 'DELIVERED'
    IN_DELIV = 'IN_DELIV'
    DELIV_FAIL = 'DELIV_FAIL'
    IN_WH = 'IN_WH'
    
    available_status = (
        (DELIV, 'Delivered'),
        (IN_DELIV, 'In delivery'),
        (DELIV_FAIL, 'Delivery failed'),
        (IN_WH, 'In warehouse'),
    )

    status = models.CharField(max_length=255, choices=available_status, default=IN_WH)    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    send_date = models.DateTimeField(auto_now=True)
    x_in_mm = models.FloatField(default=0.0)
    y_in_mm = models.FloatField(default=0.0)
    z_in_mm = models.FloatField(default=0.0)
    is_breakable = models.BooleanField(default=False)
    is_perishable = models.BooleanField(default=False)
    
    #last_delivery = models.OneToOneField(Delivery, on_delete=models.CASCADE, null=True, blank=True)
    last_delivery = models.ForeignKey(Delivery, on_delete=models.CASCADE, related_name='last_delivery')
    
    class Meta:
        verbose_name_plural = 'Packages'
        ordering = ('-created',)
        
    def get_absolute_url(self):
        return reverse("DD:package_detail",args=[self.slug])
        
    def __str__(self):
        return self.title
    
    

DD/forms.py
from django import forms
from .models import Customer

class Timeframe_form(forms.ModelForm):
    
    days = (
        ('SUNDAY', 'Sunday'),
        ('MONDAY', 'Monday'),
        ('TUESDAY', 'Tuesday'),
        ('WEDNESDAY', 'Wednesday'),
        ('THURSDAY', 'Thursday'),
        ('FRIDAY', 'Friday'),
        ('SATURDAY', 'Saturday'),
    )
    part_of_day = (
        ('MORNING', 'Morning'),
        ('AFTERNOON', 'Afternoon'),
        ('EVENING', 'Evening')
    )
    
    available_days = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                          choices=days)
    #available_parts_day = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
    #                                      choices=part_of_day)
    
    class Meta:
        model = Customer
        fields = ['available_days']

DD/views.py
from django.shortcuts import render, get_object_or_404

from .models import Package, Employee, Customer
from .forms import Timeframe_form
from django.contrib.auth.models import User

# Create your views here.

def customer_packages_all(request):
    if request.user.is_authenticated:
        packages = Package.objects.filter(purchased_by=request.user)
        return render(request, 'DD/home.html', {'packages': packages})
    return render(request, 'DD/home.html')

def customer_edit_timeframe(request):
    if request.method == 'POST':
        form = Timeframe_form(request.POST)
        user = request.user
        c = Customer.objects.get(user=user)
        if form.is_valid():
            c.available_days = request.POST['available_days']
            c.save()
            return render(request, 'DD/home.html')
    else:
        form = Timeframe_form()
        
    return render(request, 'DD/customer/timeframe.html', {'form': form,})

def all_packages(request):
    packages = Package.objects.all()
    return render(request, 'DD/home.html', {'packages': packages})

def package_detail(request, slug):
    package = get_object_or_404(Package, slug=slug)
    deliverer = Employee.objects.filter(user=package.delivered_by)[0]
    return render(request, 'DD/packages/detail.html', {'package': package, 'deliverer': deliverer})

def user_track_packages(request, package_slug):
    packages = Package.objects.filter(user=request.user)
    return render(request, 'DD/users/customer.html', {'packages': packages})

def driver_route(request):
    emp = Employee.objects.filter(user=request.user)
    return render(request, 'DD/employees/driver/routes.html', {'employee': emp})

def driver_packages(request):
    pac = Package.objects.filter(delivered_by=request.user)
    return render(request, 'DD/packages.html', {'packages': pac})



    

    

templates/DD/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Disruptive Delivery{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        {% if user.is_authenticated %}

            {% if user.employee.position == 'DRIVER' %}
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">DisruptiveDelivery</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="{% url 'DD:driver_route' %}">Routes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'DD:driver_packages' %}">Packages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Edit Packages</a>
                            </li>
                        </ul>  
                        Hi {{ user.username }}! 
                        <a href="{% url 'custom_auth:logout' %}" class="btn btn-info" role="button">Log out</a>
                    </div>
                </div>
            </nav>

            {% elif user.employee.position == 'WAREHOUSE WORKER' %}
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">DisruptiveDelivery</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse"> 
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Register Packages</a>
                            </li>
                        </ul>  
                        Hi {{ user.username }}! 
                        <a href="{% url 'custom_auth:logout' %}" class="btn btn-info" role="button">Log out</a>
                    </div>
                </div>
            </nav>

            {% elif user.employee.position == 'WAREHOUSE MANAGER'%}
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">DisruptiveDelivery</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse"> 
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Go to admin panel</a>
                            </li>
                        </ul>  
                        Hi {{ user.username }}! 
                        <a href="{% url 'custom_auth:logout' %}" class="btn btn-info" role="button">Log out</a>
                    </div>
                </div>
            </nav>
            {% else %}
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">DisruptiveDelivery</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse"> 
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="/">Check your packages</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="{% url 'DD:customer_edit_timeframe' %}">Edit your timeframe</a>
                            </li>
                        </ul>  
                        Hi {{ user.username }}! 
                        <a href="{% url 'custom_auth:logout' %}" class="btn btn-info" role="button">Log out</a>
                    </div>
                </div>
            </nav>
            {% endif %}
        
        {% else %}
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">DisruptiveDelivery</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                        </ul>  
                        <a href="/accounts/login" class="btn btn-info" role="button">Log in</a>
                    </div>
                </div>
            </nav>

        {% endif %}

    <div id="content">{% block content %} {% endblock %}</div>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
    
        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
            <i class="fab fa-github"></i>
            </a>
        </div>
        <!-- Right -->
        </section>
        <!-- Section: Social media -->
    
        <!-- Section: Links  -->
        <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>Disruptive Delivery
                </h6>
                <p>
                Everything Everywhere All At Once
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Products
                </h6>
                <p>
                <a href="#!" class="text-reset">Angular</a>
                </p>
                <p>
                <a href="#!" class="text-reset">React</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Vue</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Laravel</a>
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                Useful links
                </h6>
                <p>
                <a href="#!" class="text-reset">Pricing</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Settings</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Orders</a>
                </p>
                <p>
                <a href="#!" class="text-reset">Help</a>
                </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                <p>
                <i class="fas fa-envelope me-3"></i>
                info@example.com
                </p>
                <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
        </section>
        <!-- Section: Links  -->
    
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
</body>
</html>

templates/DD/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Get everything delivered anywhere!</h1>
        {% if user.is_authenticated %}
          Hi {{ user.username }}! What do you want to do?   
        {% else %}
          <p class="lead text-muted">Do you want something delivered? 
            <a href={% url 'custom_auth:register' %}>Make an account!</a>
          </p>
        {% endif %}

      </div>
    </div>
  </section>

  {% if user.is_authenticated and user.customer%}
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Packages</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for p in packages %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ p.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ p.get_absolute_url }}">{{ p.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{p.description}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>
  {% endif %}


</main>

{% endblock %}

templates/DD/packages.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Packages{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">You're now seeing your packages</h1>
        Hi {{ user.username }}! Here's the list of your packages
        {% for p in packages %}
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ p.image.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ p.get_absolute_url }}">{{ p.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">{{p.description}}</small>
                </div>
              </div>
            </div>
          </div>
        {% endfor%}
      </div>
    </div>
  </section>



</main>

{% endblock %}